services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: ai-kb-api
    ports:
      - "8000:8000"
    depends_on:
      - clickhouse
    volumes:
      - ./fastapi_app:/app/fastapi_app
      - ./etl:/app/etl
      - ./requirements.txt:/app/requirements.txt
      - ./data:/data
      - ./embeddings:/app/embeddings
    env_file:
      - .env
    restart: always
    networks:
      - monitor-net

  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    container_name: clickhouse
    ports:
      - "8123:8123" #HTTP
      - "9000:9000" #TCP
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: default_pass
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - monitor-net

networks:
  monitor-net:
    driver: bridge